# xrp-ledger.toml  — host at: https://lyra-slug.github.io/.well-known/xrp-ledger.toml

[METADATA]
orgName = "ZLUG"
orgWebsite = "https://lyra-slug.github.io"
description = "ZLUG is a meme project on XRPL. Not financial advice."

# --- Public accounts you disclose ---
[[ACCOUNTS]]
address = "rpyhmk2oYXrGrAw6wniiouwVXyr2mFwucJ"         # ZLUGSELF (issuer)
desc    = "Issuer account — mints ZLUG."

# --- Token definition (ZLUG) ---
[[CURRENCIES]]
code              = "ZLUG"
issuer            = "rpyhmk2oYXrGrAw6wniiouwVXyr2mFwucJ"
name              = "ZLUG"
symbol            = "ZLUG"
display_decimals  = 0
network           = "main"
icon              = "https://lyra-slug.github.io/.well-known/ZLUG-logo.PNG"
logo             = "https://lyra-slug.github.io/.well-known/ZLUG-logo.png
website           = "https://lyra-slug.github.io"
info              = "Community meme token. No presale. 69M max supply. 69% of NFT proceeds burnt."
transfer_fee      = 0
