[CURRENCIES]
code = "ZLUG"
issuer = "rpyhmk2oYXrGrAw6wniiouwVXyr2mFwucJ"
display_decimals = 0
icon = "https://lyra-slug.github.io/.well-known/ZLUG-logo.PNG"
desc = "ZLUG — community meme token. Max supply 69,000,000. 69% of NFT proceeds burnt."
