[CURRENCIES]
code = "ZLUG"
issuer = "rISSUER_ADDRESS_HERE"
display_decimals = 0
icon = "https://raw.githubusercontent.com/<user>/<repo>/main/ZLUG-logo.PNG"
desc = "ZLUG — community meme token. Max supply 69,000,000. 69% of NFT proceeds burnt."
